class AlShaikh{
  final String name;
  final String image;
  final String url;
  AlShaikh({
    required this.name,
    required this.image,
    required this.url,
  });
}

List<AlShaikh> allReaders=[
  AlShaikh(name: 'عبدالباسط عبدالصمد', image: 'assets/images/1.png', url: '13.mp3quran.net/basit_mjwd'),
  AlShaikh(name: 'محمد صديق المنشاوي ', image: 'assets/images/2.jpg', url: '10.mp3quran.net/minsh'),
  // AlShaikh(name: 'محمد رفعت', image: 'assets/images/3.jpg', url: '14.mp3quran.net/refat'),
  AlShaikh(name: 'محمود علي البنا', image: 'assets/images/4.jpg', url: '8.mp3quran.net/bna'),
  AlShaikh(name: 'محمود خليل الحصري', image: 'assets/images/5.jpg', url: '13.mp3quran.net/husr'),
  AlShaikh(name: 'محمد أيوب', image: 'assets/images/6.jpg', url: '8.mp3quran.net/ayyub'),
  AlShaikh(name: 'فارس عباد', image: 'assets/images/7.jpg', url: '8.mp3quran.net/frs_a'),
  AlShaikh(name: 'ناصر القطامي', image: 'assets/images/8.jpg', url: '6.mp3quran.net/qtm'),
  AlShaikh(name: 'ياسر الدوسري', image: 'assets/images/9.jpg', url: '11.mp3quran.net/yasser'),
  AlShaikh(name: 'ماهر المعيقلي', image: 'assets/images/10.jpg', url: '12.mp3quran.net/maher'),
  AlShaikh(name: 'صلاح بو خاطر', image: 'assets/images/11.jpg', url: '8.mp3quran.net/bu_khtr'),
  AlShaikh(name: 'أحمد العجمي', image: 'assets/images/12.jpg', url: '10.mp3quran.net/ajm'),
  AlShaikh(name: 'عبد الرحمن السديس', image: 'assets/images/13.jpg', url: '11.mp3quran.net/sds'),
  AlShaikh(name: 'سعد الغامدي', image: 'assets/images/14.jpg', url: '7.mp3quran.net/s_gmd'),
  AlShaikh(name: 'مشاري راشد العفاسي', image: 'assets/images/15.jpg', url: '8.mp3quran.net/afs'),
  AlShaikh(name: 'عبدالله المطرود', image: 'assets/images/16.jpg', url: '8.mp3quran.net/mtrod'),
  AlShaikh(name: 'اسلام صبحي', image: 'assets/images/17.jpg', url: 'https://ia801406.us.archive.org/12/items/002_20221103_202211'),
];

class QuranChapter {
  final String nameArabic;
  final String number;
  final int pageNumber;
  QuranChapter({
    required this.nameArabic,
    required this.number,
    required this.pageNumber,
  });
}

List<QuranChapter> hollyQuraan=[
  QuranChapter(nameArabic: "الفاتحة", number: "001", pageNumber: 1),
  QuranChapter(nameArabic: "البقرة", number: "002", pageNumber: 2),
  QuranChapter(nameArabic: "آل عمران", number: "003", pageNumber: 45),
  QuranChapter(nameArabic: "النساء", number: "004", pageNumber: 69),
  QuranChapter(nameArabic: "المائدة", number: "005", pageNumber: 95),
  QuranChapter(nameArabic: "الأنعام", number: "006", pageNumber: 115),
  QuranChapter(nameArabic: "الأعراف", number: "007", pageNumber: 136),
  QuranChapter(nameArabic: "الأنفال", number: "008", pageNumber: 160),
  QuranChapter(nameArabic: "التوبة", number: "009", pageNumber: 169),
  QuranChapter(nameArabic: "يونس", number: "010", pageNumber: 187),
  QuranChapter(nameArabic: "هود", number: "011", pageNumber: 199),
  QuranChapter(nameArabic: "يوسف", number: "012", pageNumber: 212),
  QuranChapter(nameArabic: "الرعد", number: "013", pageNumber: 225),
  QuranChapter(nameArabic: "إبراهيم", number: "014", pageNumber: 231),
  QuranChapter(nameArabic: "الحجر", number: "015", pageNumber: 237),
  QuranChapter(nameArabic: "النحل", number: "016", pageNumber: 242),
  QuranChapter(nameArabic: "الإسراء", number: "017", pageNumber: 255),
  QuranChapter(nameArabic: "الكهف", number: "018", pageNumber: 266),
  QuranChapter(nameArabic: "مريم", number: "019", pageNumber: 277),
  QuranChapter(nameArabic: "طه", number: "020", pageNumber: 284),
  QuranChapter(nameArabic: "الأنبياء", number: "021", pageNumber: 294),
  QuranChapter(nameArabic: "الحج", number: "022", pageNumber: 302),
  QuranChapter(nameArabic: "المؤمنون", number: "023", pageNumber: 311),
  QuranChapter(nameArabic: "النور", number: "024", pageNumber: 319),
  QuranChapter(nameArabic: "الفرقان", number: "025", pageNumber: 329),
  QuranChapter(nameArabic: "الشعراء", number: "026", pageNumber: 335),
  QuranChapter(nameArabic: "النمل", number: "027", pageNumber: 345),
  QuranChapter(nameArabic: "القصص", number: "028", pageNumber: 354),
  QuranChapter(nameArabic: "العنكبوت", number: "029", pageNumber: 364),
  QuranChapter(nameArabic: "الروم", number: "030", pageNumber: 371),
  QuranChapter(nameArabic: "لقمان", number: "031", pageNumber: 377),
  QuranChapter(nameArabic: "السجدة", number: "032", pageNumber: 381),
  QuranChapter(nameArabic: "الأحزاب", number: "033", pageNumber: 383),
  QuranChapter(nameArabic: "سبأ", number: "034", pageNumber: 393),
  QuranChapter(nameArabic: "فاطر", number: "035", pageNumber: 399),
  QuranChapter(nameArabic: "يس", number: "036", pageNumber: 404),
  QuranChapter(nameArabic: "الصافات", number: "037", pageNumber: 410),
  QuranChapter(nameArabic: "ص", number: "038", pageNumber: 414),
  QuranChapter(nameArabic: "الزمر", number: "039", pageNumber: 422),
  QuranChapter(nameArabic: "غافر", number: "040", pageNumber: 431),
  QuranChapter(nameArabic: "فصلت", number: "041", pageNumber: 439),
  QuranChapter(nameArabic: "الشورى", number: "042", pageNumber: 445),
  QuranChapter(nameArabic: "الزخرف", number: "043", pageNumber: 451),
  QuranChapter(nameArabic: "الدخان", number: "044", pageNumber: 457),
  QuranChapter(nameArabic: "الجاثية", number: "045", pageNumber: 460),
  QuranChapter(nameArabic: "الأحقاف", number: "046", pageNumber: 464),
  QuranChapter(nameArabic: "محمد", number: "047", pageNumber: 468),
  QuranChapter(nameArabic: "الفتح", number: "048", pageNumber: 472),
  QuranChapter(nameArabic: "الحجرات", number: "049", pageNumber: 477),
  QuranChapter(nameArabic: "ق", number: "050", pageNumber: 479),
  QuranChapter(nameArabic: "الذاريات", number: "051", pageNumber: 482),
  QuranChapter(nameArabic: "الطور", number: "052", pageNumber: 485),
  QuranChapter(nameArabic: "النجم", number: "053", pageNumber: 487),
  QuranChapter(nameArabic: "القمر", number: "054", pageNumber: 490),
  QuranChapter(nameArabic: "الرحمن", number: "055", pageNumber: 493),
  QuranChapter(nameArabic: "الواقعة", number: "056", pageNumber: 496),
  QuranChapter(nameArabic: "الحديد", number: "057", pageNumber: 499),
  QuranChapter(nameArabic: "المجادلة", number: "058", pageNumber: 504),
  QuranChapter(nameArabic: "الحشر", number: "059", pageNumber: 507),
  QuranChapter(nameArabic: "الممتحنة", number: "060", pageNumber: 510),
  QuranChapter(nameArabic: "الصف", number: "061", pageNumber: 513),
  QuranChapter(nameArabic: "الجمعة", number: "062", pageNumber: 515),
  QuranChapter(nameArabic: "المنافقون", number: "063", pageNumber: 516),
  QuranChapter(nameArabic: "التغابن", number: "064", pageNumber: 518),
  QuranChapter(nameArabic: "الطلاق", number: "065", pageNumber: 520),
  QuranChapter(nameArabic: "التحريم", number: "066", pageNumber: 522),
  QuranChapter(nameArabic: "الملك", number: "067", pageNumber: 524),
  QuranChapter(nameArabic: "القلم", number: "068", pageNumber: 526),
  QuranChapter(nameArabic: "الحاقة", number: "069", pageNumber: 529),
  QuranChapter(nameArabic: "المعارج", number: "070", pageNumber: 531),
  QuranChapter(nameArabic: "نوح", number: "071", pageNumber: 533),
  QuranChapter(nameArabic: "الجن", number: "072", pageNumber: 534),
  QuranChapter(nameArabic: "المزمل", number: "073", pageNumber: 537),
  QuranChapter(nameArabic: "المدثر", number: "074", pageNumber: 538),
  QuranChapter(nameArabic: "القيامة", number: "075", pageNumber: 540),
  QuranChapter(nameArabic: "الإنسان", number: "076", pageNumber: 542),
  QuranChapter(nameArabic: "المرسلات", number: "077", pageNumber: 545),
  QuranChapter(nameArabic: "النبأ", number: "078", pageNumber: 547),
  QuranChapter(nameArabic: "النازعات", number: "079", pageNumber: 548),
  QuranChapter(nameArabic: "عبس", number: "080", pageNumber: 549),
  QuranChapter(nameArabic: "التكوير", number: "081", pageNumber: 550),
  QuranChapter(nameArabic: "الإنفطار", number: "082", pageNumber: 551),
  QuranChapter(nameArabic: "المطففين", number: "083", pageNumber: 552),
  QuranChapter(nameArabic: "الإنشقاق", number: "084", pageNumber: 553),
  QuranChapter(nameArabic: "البروج", number: "085", pageNumber: 554),
  QuranChapter(nameArabic: "الطارق", number: "086", pageNumber: 555),
  QuranChapter(nameArabic: "الأعلى", number: "087", pageNumber: 556),
  QuranChapter(nameArabic: "الغاشية", number: "088", pageNumber: 557),
  QuranChapter(nameArabic: "الفجر", number: "089", pageNumber: 557),
  QuranChapter(nameArabic: "البلد", number: "090", pageNumber: 559),
  QuranChapter(nameArabic: "الشمس", number: "091", pageNumber: 559),
  QuranChapter(nameArabic: "الليل", number: "092", pageNumber: 560),
  QuranChapter(nameArabic: "الضحى", number: "093", pageNumber: 561),
  QuranChapter(nameArabic: "الشرح", number: "094", pageNumber: 561),
  QuranChapter(nameArabic: "التين", number: "095", pageNumber: 562),
  QuranChapter(nameArabic: "العلق", number: "096", pageNumber: 562),
  QuranChapter(nameArabic: "القدر", number: "097", pageNumber: 563),
  QuranChapter(nameArabic: "البينة", number: "098", pageNumber: 563),
  QuranChapter(nameArabic: "الزلزلة", number: "099", pageNumber: 564),
  QuranChapter(nameArabic: "العاديات", number: "100", pageNumber: 564),
  QuranChapter(nameArabic: "القارعة", number: "101", pageNumber: 565),
  QuranChapter(nameArabic: "التكاثر", number: "102", pageNumber: 565),
  QuranChapter(nameArabic: "العصر", number: "103", pageNumber: 566),
  QuranChapter(nameArabic: "الهمزة", number: "104", pageNumber: 566),
  QuranChapter(nameArabic: "الفيل", number: "105", pageNumber: 566),
  QuranChapter(nameArabic: "قريش", number: "106", pageNumber: 567),
  QuranChapter(nameArabic: "الماعون", number: "107", pageNumber: 567),
  QuranChapter(nameArabic: "الكوثر", number: "108", pageNumber: 567),
  QuranChapter(nameArabic: "الكافرون", number: "109", pageNumber: 568),
  QuranChapter(nameArabic: "النصر", number: "110", pageNumber: 568),
  QuranChapter(nameArabic: "المسد", number: "111", pageNumber: 568),
  QuranChapter(nameArabic: "الإخلاص", number: "112", pageNumber: 569),
  QuranChapter(nameArabic: "الفلق", number: "113", pageNumber: 569),
  QuranChapter(nameArabic: "الناس", number: "114", pageNumber: 569),
];
