import 'package:flutter/material.dart';
import 'package:quran_app/material.dart';
import 'package:quran_app/our_widgets.dart';
import 'package:quran_app/screens/rageh_hefzzak/questions.dart';

class ChooseCategory extends StatelessWidget {
  // List<String> list = [
  //   "الفاتحة",
  //   "البقرة",
  //   "آل عمران",
  //   "النساء",
  //   "المائدة",
  //   "الأنعام",
  //   "الأعراف",
  //   "الأنفال",
  //   "التوبة",
  //   "يونس",
  //   "هود",
  //   "يوسف",
  //   "الرعد",
  //   "إبراهيم",
  //   "الحجر",
  //   "النحل",
  //   "الإسراء",
  //   "الكهف",
  //   "مريم",
  //   "طه",
  //   "الأنبياء",
  //   "الحج",
  //   "المؤمنون",
  //   "النور",
  //   "الفرقان",
  //   "الشعراء",
  //   "النمل",
  //   "القصص",
  //   "العنكبوت",
  //   "الروم",
  //   "لقمان",
  //   "السجدة",
  //   "الأحزاب",
  //   "سبأ",
  //   "فاطر",
  //   "يس",
  //   "الصافات",
  //   "ص",
  //   "الزمر",
  //   "غافر",
  //   "فصلت",
  //   "الشورى",
  //   "الزخرف",
  //   "الدخان",
  //   "الجاثية",
  //   "الأحقاف",
  //   "محمد",
  //   "الفتح",
  //   "الحجرات",
  //   "ق",
  //   "الذاريات",
  //   "الطور",
  //   "النجم",
  //   "القمر",
  //   "الرحمن",
  //   "الواقعة",
  //   "الحديد",
  //   "المجادلة",
  //   "الحشر",
  //   "الممتحنة",
  //   "الصف",
  //   "الجمعة",
  //   "المنافقون",
  //   "التغابن",
  //   "الطلاق",
  //   "التحريم",
  //   "الملك",
  //   "القلم",
  //   "الحاقة",
  //   "المعارج",
  //   "نوح",
  //   "الجن",
  //   "المزمل",
  //   "المدثر",
  //   "القيامة",
  //   "الإنسان",
  //   "المرسلات",
  //   "النبأ",
  //   "النازعات",
  //   "عبس",
  //   "التكوير",
  //   "الإنفطار",
  //   "المطففين",
  //   "الإنشقاق",
  //   "البروج",
  //   "الطارق",
  //   "الأعلى",
  //   "الغاشية",
  //   "الفجر",
  //   "البلد",
  //   "الشمس",
  //   "الليل",
  //   "الضحى",
  //   "الشرح",
  //   "التين",
  //   "العلق",
  //   "القدر",
  //   "البينة",
  //   "الزلزلة",
  //   "العاديات",
  //   "القارعة",
  //   "التكاثر",
  //   "العصر",
  //   "الهمزة",
  //   "الفيل",
  //   "قريش",
  //   "الماعون",
  //   "الكوثر",
  //   "الكافرون",
  //   "النصر",
  //   "المسد",
  //   "الإخلاص",
  //   "الفلق",
  //   "الناس",
  // ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: myAppBar(context: context, title: 'راجع حفظك'),
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Colors.blueGrey[300]!,
              Colors.blueGrey[600]!,
            ],
          ),
        ),
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: SingleChildScrollView(
            child: Column(
              children: [
                Container(
                  width: double.infinity,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10.0),
                    gradient: LinearGradient(
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                      colors: [
                        Colors.blueGrey[400]!,
                        Colors.blueGrey[700]!,
                      ],
                    ),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        'اختر السورة',
                        style: TextStyle(
                            fontSize: 24.0, fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                ),
                SizedBox(
                  height: 10.0,
                ),
                ListView.separated(
                    shrinkWrap: true,
                    physics: NeverScrollableScrollPhysics(),
                    itemBuilder: (context, index) => chapterItem(
                        context: context,
                        from: chooseCList,
                        index: index,
                        fav: false,
                        navScreen: Questions(chapter: chooseCList[index],)),
                    separatorBuilder: (context , index ) => SizedBox(height: 10.0,),
                    itemCount: 114),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
